const CONFIG = {
  SHEET_NAMES: {
    WORKS: 'works',
    PARAMETERS: 'parameters',
    FORM: 'form',
    PROJECTS: 'projects',
    PERSONS: 'persons', //contactシート
    MEMBERS: 'members',
    MAIN: 'main',
    TASKS: 'tasks',
  },
  HEADER_NAMES: {
    MANAGE_ID: '管理番号',
    WORK_ID: '制作番号',
    WORK_TITLE: '制作タイトル',
    PROJECT_ID: '案件番号',
    PROJECT_TITLE: '案件タイトル',
    WORK_GENRE: 'ジャンル',
    PROJECT_FOLDER: '案件フォルダ',
    PROJECT_DOCUMENT: '案件ドキュメント',
    CLIENT: '依頼者',
    EMAIL: 'E-mail 1 - Value',
    SLACK_ID: 'Slack ID',
    STATUS: 'ステータス',
    CONTENT: '内容',
    DESIGN: 'デザイン要項',
    REGULATION: '入稿規定',
    NOTE: '依頼備考',
    HEARING: 'ヒアリング',
    REFERENCE: '参考物',
    OTHER_MEMO: 'その他メモ',
    USED_TOOLS: '制作アプリ',
    DELIVERY_COUNT: '成果物数',
    WILL_MAKE_NEXT: '来年も作るべきか',
  },
  HEADER_NAMES_CONTACT: {
    EMAIL: 'E-mail 1 - Value',
    SLACK_ID: 'Slack ID',
  },
  PARAM_KEYS: {
    CONTACT_SHEET_ID: 'contactSheet.id',
    SYSTEM_START_YEAR: 'system.startYear',
    WORK_FOLDER_ID: 'workInfo.url.workFolder',
    WORK_SHEET_ID: 'workInfo.url.workSheet',
    REGISTRATION_FORM_ID: 'registrationForm.id',
    PROJ_DOC_ID: 'workInfo.url.projDoc',
    PROJ_FOLDER_ID: 'workInfo.url.projFolder',
  },
  PROPERTIES: {
    SLACK_WORKFLOW_URL: 'slackWorkflow_notifyRequest_WebReqestUrl',
    SLACK_ADMIN_EMAIL: 'slackAdminEmail',
    RESOURCE_SHEET_ID: 'sheetId_resource',
  },
  STATUS: {
    STEP1: '依頼受付',
    STEP2: '初回ヒアリング',
    STEP3: '制作',
    STEP4: 'ブラッシュアップ',
    STEP5: '班長承認',
    STEP6: '納品',
    CANCELLED: '依頼取消',
  },
  TASK_STATUS: {
    NOT_STARTED: '未着手',
    IN_PROGRESS: '実行中',
    DONE: '完了',
  },
  NAME_PREFIX: {
    MATERIAL: '【素材】',
    DELIVERY: '【納品】',
    WORKSHEET: '【制作管理】',
    PROJDOC: '【案件ドキュメント】',
  },
  UI: {
    RESOURCE_SHEET_LINK_TEXT: 'リソース管理シート',
  },
  SYSTEM_COMMANDS: {
    DONT_SEND_NOTIFICATION: 'dontSendNotification',
  },
};